import { Option } from "@/components/ui/multipleSelector";

export const categoriesOption: Option[] = [
    { value: "Technology", label: "Technology" },
    { value: "Science", label: "Science" },
    { value: "Art", label: "Art" },
    { value: "Music", label: "Music" },
    { value: "Business", label: "Business" },
    { value: "Education", label: "Education" },
    { value: "Health", label: "Health" },
    { value: "Sport", label: "Sport" },
    { value: "Entertainment", label: "Entertainment" },
    { value: "Other", label: "Other" }
];

export const tagsOption: Option[] = [
    { value: "Web Development", label: "Web Development" },
    { value: "Mobile Development", label: "Mobile Development" },
    { value: "AI/ML", label: "AI/ML" },
    { value: "Data Science", label: "Data Science" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "Cloud Computing", label: "Cloud Computing" },
    { value: "IOT", label: "IOT" },
    { value: "Blockchain", label: "Blockchain" },
    { value: "Physics", label: "Physics" },
    { value: "Chemistry", label: "Chemistry" },
    { value: "Biology", label: "Biology" },
    { value: "Astronomy", label: "Astronomy" },
    { value: "Earth Science", label: "Earth Science" },
    { value: "Environmental Science", label: "Environmental Science" },
    { value: "Painting", label: "Painting" },
    { value: "Sculpture", label: "Sculpture" },
    { value: "Digital Art", label: "Digital Art" },
    { value: "Photography", label: "Photography" },
    { value: "Literature", label: "Literature" },
    { value: "Performing Arts", label: "Performing Arts" },
    { value: "Classical", label: "Classical" },
    { value: "Jazz", label: "Jazz" },
    { value: "Rock", label: "Rock" },
    { value: "Pop", label: "Pop" },
    { value: "Hip-Hop", label: "Hip-Hop" },
    { value: "Electronic", label: "Electronic" },
    { value: "Marketing", label: "Marketing" },
    { value: "Finance", label: "Finance" },
    { value: "Entrepreneurship", label: "Entrepreneurship" },
    { value: "Management", label: "Management" },
    { value: "Sales", label: "Sales" },
    { value: "Human Resources", label: "Human Resources" },
    { value: "E-Learning", label: "E-Learning" },
    { value: "Curriculum Development", label: "Curriculum Development" },
    { value: "Educational Technology", label: "Educational Technology" },
    { value: "Classroom Management", label: "Classroom Management" },
    { value: "Special Education", label: "Special Education" },
    { value: "Mental Health", label: "Mental Health" },
    { value: "Nutrition", label: "Nutrition" },
    { value: "Fitness", label: "Fitness" },
    { value: "Medicine", label: "Medicine" },
    { value: "Public Health", label: "Public Health" },
    { value: "Wellness", label: "Wellness" },
    { value: "Football", label: "Football" },
    { value: "Basketball", label: "Basketball" },
    { value: "Tennis", label: "Tennis" },
    { value: "Running", label: "Running" },
    { value: "Swimming", label: "Swimming" },
    { value: "Fitness", label: "Fitness" },
    { value: "Movies", label: "Movies" },
    { value: "TV Shows", label: "TV Shows" },
    { value: "Video Games", label: "Video Games" },
    { value: "Comics", label: "Comics" },
    { value: "Theatre", label: "Theatre" },
    { value: "Animation", label: "Animation" },
    { value: "Travel", label: "Travel" },
    { value: "Food", label: "Food" },
    { value: "DIY", label: "DIY" },
    { value: "Gardening", label: "Gardening" },
    { value: "Pets", label: "Pets" },
    { value: "Personal Development", label: "Personal Development" }
];